import Head from 'next/head'
import Header from '@/components/Header'
import Navbar from '@/components/Navbar'
import Results from '@/components/Results'
import requests from 'utils/requests'

export default function Home({data}) {
  console.log('results', data.results)
  return (
    <>
      <Head>
        <title>IMDB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header/>

      {/* Navbar */}
      <Navbar/>

      {/* Results */}
      <Results results={data.results}/>
    </>
  )
}

export async function getServerSideProps (context) {
  const genre = context.query.genre || 'fetchTrending'
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre].url}`).then(res => res.json())
  console.log('request', request)
  return {
    props: {
      data: request,
    }
  }
}